[build]
  command = "pnpm prisma generate && pnpm run build"
  functions = "netlify/functions"
  publish = "dist/spa"


[functions."api"]
  node_bundler = "esbuild"
  external_node_modules = ["@neondatabase/serverless", "@prisma/client"]

[env.production]
  variables = { NODE_ENV = "production" }
  
[[redirects]]
  force = true
  from = "/api/*"
  to = "/.netlify/functions/api"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
